from mininet.topo import Topo

class MyTopo( Topo ):

	def __init__( self ):

        # Initialize topology
		Topo.__init__( self )

        # Add hosts and switches
		h1 = self.addHost( 'h1' )
		h2 = self.addHost( 'h2' )
		h3 = self.addHost( 'h3' )
		h4 = self.addHost( 'h4' )
		h5 = self.addHost( 'h5' )
		h6 = self.addHost( 'h6' )
		h7 = self.addHost( 'h7' )
		h8 = self.addHost( 'h8' )
		h9 = self.addHost( 'h9' )
		h10 = self.addHost( 'h10' )
		h11 = self.addHost( 'h11' )
		h12 = self.addHost( 'h12' )
		h13 = self.addHost( 'h13' )
		h14 = self.addHost( 'h14' )
		h15 = self.addHost( 'h15' )
		h16 = self.addHost( 'h16' )
		h17 = self.addHost( 'h17' )
		h18 = self.addHost( 'h18' )
		h19 = self.addHost( 'h19' )
		h20 = self.addHost( 'h20' )
		s1 = self.addSwitch( 's1' )
		s2 = self.addSwitch( 's2' )
		s3 = self.addSwitch( 's3' )
		s4 = self.addSwitch( 's4' )
		s5 = self.addSwitch( 's5' )
		s6 = self.addSwitch( 's6' )
		s7 = self.addSwitch( 's7' )
		s8 = self.addSwitch( 's8' )
		s9 = self.addSwitch( 's9' )
		s10 = self.addSwitch( 's10' )
		s11 = self.addSwitch( 's11' )
		s12 = self.addSwitch( 's12' )

        # Add links
		self.addLink( h1, s1 )
		self.addLink( h2, s1 )
		self.addLink( h3, s2 )
		self.addLink( h4, s2 )
		self.addLink( h5, s3 )
		self.addLink( h6, s3 )
		self.addLink( h7, s4 )
		self.addLink( h8, s5 )
		self.addLink( h9, s5 )
		self.addLink( h10, s6 )
		self.addLink( h11, s6 )
		self.addLink( h12, s7 )
		self.addLink( h13, s8 )
		self.addLink( h14, s9 )
		self.addLink( h15, s9 )
		self.addLink( h16, s10 )
		self.addLink( h17, s10 )
		self.addLink( h18, s11 )
		self.addLink( h19, s12 )
		self.addLink( h20, s12 )


		self.addLink( s1, s2 )
		self.addLink( s1, s3 )
		self.addLink( s1, s8 )
		self.addLink( s2, s7 )
		self.addLink( s2, s8 )
		self.addLink( s2, s9 )
		self.addLink( s2, s11 )
		self.addLink( s3, s4 )
		self.addLink( s4, s6 )
		self.addLink( s4, s8 )
		self.addLink( s5, s6 )
		self.addLink( s5, s7 )
		self.addLink( s6, s7 )
		self.addLink( s6, s10 )
		self.addLink( s6, s11 )
		self.addLink( s6, s12 )
		self.addLink( s9, s10 )
		self.addLink( s10, s12 )
		self.addLink( s11, s12 )

topos = { 'mytopo': ( lambda: MyTopo() ) }
